# Generated by Django 5.2.7 on 2025-10-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                help_text="Укажите имя", max_length=150, verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                help_text="Укажите фамилию", max_length=150, verbose_name="Фамилия"
            ),
        ),
    ]
