# Generated by Django 5.2.7 on 2025-10-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="укажите название задачи",
                        max_length=250,
                        verbose_name="Название задачи",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        help_text="Укажите дату и время, когда должно быть готово",
                        verbose_name="Когда должно быть готово",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "В работе"), ("completed", "Завершена")],
                        default="active",
                        help_text="Укажите статус задачи",
                        max_length=9,
                        verbose_name="Статус задачи",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
    ]
