# Generated by Django 5.2.7 on 2025-10-17 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_owner_alter_task_executor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["-id"],
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
    ]
